name: Build and Test

on:
  pull_request:
    branches: [ "main" ]

env:
  SOURCE_DIR: ${{github.workspace}}/source/
  UT_SOURCE_DIR: ${{github.workspace}}/source/LinkedList.UnitTest/

jobs:
  run-mutation-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - name: Restore dependencies
      working-directory: ${{env.SOURCE_DIR}}
      run: dotnet restore
    - name: Restore tool dependencies
      working-directory: ${{env.SOURCE_DIR}}
      run: dotnet tool restore
    - name: Build and Unit-Test
      working-directory: ${{env.SOURCE_DIR}}
      run: dotnet test
    - name: Do mutation analysis
      working-directory: ${{env.UT_SOURCE_DIR}}
      run: dotnet stryker --since:$(git merge-base HEAD origin/${{ github.base_ref }})
    - uses: actions/upload-artifact@v3
      name: Upload stryker report
      with:
        name: stryker-report
        path: ${{env.UT_SOURCE_DIR}}/**/mutation-report.html
        retention-days: 3